### ISSUE TITLE
don't make all fields required on follow up form

### ISSUE THREAD

**Issue by radhikajain** [SaturdayNeighborhoodHealthClinic/osler#36] opened 2015-09-15 23:35 UTC
particularly relevant for "referral follow up"

**Comment by justinrporter** [comment] 2015-09-16 02:11
I am not sure that this is the right way to handle this. In particular, we would hopefully have a form that more accurately reflects the possibilities. This is thus a duplicate of #30 .

**Closed** 2015-09-16 02:12 UTC
Labels: duplicate
